# Generated by Django 2.1.4 on 2019-03-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0003_auto_20190308_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
