# Generated by Django 2.1.4 on 2019-03-06 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0002_perfil_imagen'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='profile',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='perfiles.Perfil'),
        ),
    ]
