# Generated by Django 2.1.4 on 2019-03-06 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='profile',
            new_name='perfil',
        ),
    ]
